# Known failure: https://dfinity.atlassian.net/browse/EM-7
name: key-manager-example
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - cdk/key_manager_example/**
      - cdk/utils/**
      - cdk/types/**
      - cdk/test_utils/**
      - sdk/ic_vetkd_sdk_key_manager/**
      - sdk/ic_vetkd_sdk_key_manager_example/**
      - sdk/ic_vetkd_sdk_utils/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/key-manager-example.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  key-manager-example-darwin:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Provision Darwin
        run: |
          bash .github/workflows/provision-darwin.sh
          brew install llvm
          corepack enable pnpm
      - name: Key Manager Example Darwin
        run: |
          pushd cdk/key_manager_example
          dfx start --background -vv
          make mock
          eval $(make export-cmd)
          popd
          pushd sdk/ic_vetkd_sdk_key_manager_example
          pnpm install
          pnpm test
  key-manager-example-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Provision Linux
        run: |
          bash .github/workflows/provision-linux.sh
          corepack enable pnpm
      - name: Key Manager Example Linux
        run: |
          pushd cdk/key_manager_example
          dfx start --background -vv
          make mock
          eval $(make export-cmd)
          popd
          pushd sdk/ic_vetkd_sdk_key_manager_example
          pnpm install
          pnpm test