name: SDK Utils CI
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - sdk/ic_vetkd_sdk_utils/**
      - .github/workflows/sdk_utils.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  sdk_utils_tests_linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          sudo apt-get install nodejs
          corepack enabled pnpm
      - name: SDK Tests and Lint
        run: |
          set -eExuo pipefail
          cd sdk/ic_vetkd_sdk_utils
          pnpm install
          pnpm run build
          pnpm run test
          pnpm run lint

  sdk_utils_tests_mac:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          brew install nodejs
          corepack enabled pnpm
      - name: SDK Tests and Lint
        run: |
          set -eExuo pipefail
          cd sdk/ic_vetkd_sdk_utils
          pnpm install
          pnpm run build
          pnpm run test
          pnpm run lint
